apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    project: roboshop
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        tier: app
    spec:
      containers:
        - name: nginx
          image: nginx:{{ .Values.deployment.imageVersion }}
