apiVersion: v1
kind: Service
metadata:
  name: nginx-service-lb
  labels:
    project: roboshop
    tier: app
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.targetPort }}